import 'package:flutter/widgets.dart';
import 'package:utpl_totem_oficial/app/themes/metro_ui_icons.dart';

class CategoryServiceIcon {
  static IconData categoryServiceIcon(String name) {
    switch (name) {
      case 'calendar':
        return MetroUi.calendar;
      case 'mail':
        return MetroUi.mail;
      case 'trophy':
        return MetroUi.trophy;
      case 'file-download':
        return MetroUi.file_download;
      case 'users':
        return MetroUi.users;
      case 'lock':
        return MetroUi.lock;
      case 'windows':
        return MetroUi.windows;
      case 'broadcast':
        return MetroUi.broadcast;
      case 'phonelink':
        return MetroUi.phonelink;
      case 'perm-phone-msg':
        return MetroUi.perm_phone_msg;
      case 'tag':
        return MetroUi.tag;
      case 'earth2':
        return MetroUi.earth2;
      case 'checkmark':
        return MetroUi.checkmark;
      case 'contacts-mail':
        return MetroUi.contacts_mail;
      case 'folder-open':
        return MetroUi.folder_open;
      case 'file-text':
        return MetroUi.file_text;
      case 'profile':
        return MetroUi.profile;
      case 'files-empty':
        return MetroUi.files_empty;
      case 'school':
        return MetroUi.school;
      case 'attachment':
        return MetroUi.attachment;
      case 'redo':
        return MetroUi.redo;
      case 'drive':
        return MetroUi.drive1;
      case 'upload':
        return MetroUi.upload;
      case 'list':
        return MetroUi.list;
      case 'organization':
        return MetroUi.organization;
      case 'insert-template':
        return MetroUi.insert_template;
      case 'clipboard':
        return MetroUi.clipboard;
      case 'chart-pie':
        return MetroUi.chart_pie;
      case 'chart-dots':
        return MetroUi.chart_dots;
      case 'dollar':
        return MetroUi.dollar;
      case 'books':
        return MetroUi.books;
      case 'folder-special':
        return MetroUi.folder_special;
      case 'eye':
        return MetroUi.eye;
      case 'home':
        return MetroUi.home;
      case 'display':
        return MetroUi.display;
      case 'mobile':
        return MetroUi.mobile;
      case 'laptop':
        return MetroUi.laptop;
      case 'tablet-landscape':
        return MetroUi.tablet_landscape;
      case 'stack':
        return MetroUi.stack;
      case 'file-archive':
        return MetroUi.file_archive;
      case 'linux':
        return MetroUi.linux;
      case 'menu':
        return MetroUi.menu;
      case 'file-binary':
        return MetroUi.file_binary;
      case 'wifi-full':
        return MetroUi.wifi_full;
      case 'security':
        return MetroUi.security;
      case 'contacts-dialer':
        return MetroUi.contacts_dialer;
      case 'medkit':
        return MetroUi.medkit;
      case 'bus':
        return MetroUi.bus;
      case 'user-check':
        return MetroUi.user_check;
      case 'vpn-lock':
        return MetroUi.vpn_lock;
      case 'microscope':
        return MetroUi.microscope;
      case 'search':
        return MetroUi.search;
      case 'compass2':
        return MetroUi.compass2;
      case 'camera':
        return MetroUi.camera;
      case 'bubbles':
        return MetroUi.bubbles;
      case 'stackoverflow':
        return MetroUi.stackoverflow;
      case 'pencil':
        return MetroUi.pencil;
      case 'lab':
        return MetroUi.lab;
      case 'star-full':
        return MetroUi.star_full;
      default:
        return MetroUi.not;
    }
  }
}
